OPTIONAL
{
  ?task prof:hasTaskParameter ?Taskparam .  
}

OPTIONAL
{
   ?task prof:hasTaskParameter ?Taskparam .
   ?Taskparam prof:hasType ?Taskparamtype .
   FILTER ( ?Taskparamtype = //paramt// )
}