OPTIONAL
{
  ?task prof:hasTaskFormalInputParameter ?locTaskparam .  
   {
    ?locTaskparam prof:refersExactlyTo ?Taskparam .
   }
   UNION
   {
     ?locTaskparam prof:refersAsNewTo ?Taskparam .
   }
}

OPTIONAL
{
   ?task prof:hasTaskFormalInputParameter ?locTaskparam .
   {
    ?locTaskparam prof:refersExactlyTo ?Taskparam .
   }
   UNION
   {
     ?locTaskparam prof:refersAsNewTo ?Taskparam .
   }
   ?Taskparam prof:hasType ?Taskparamtype .
   FILTER ( ?Taskparamtype = //paramt// )
}

OPTIONAL
{
  ?task prof:hasTaskInputParameterTemplate ?locTaskparam .  
  {
    ?locTaskparam prof:refersExactlyTo ?Taskparam .
   }
   UNION
   {
     ?locTaskparam prof:refersAsNewTo ?Taskparam .
   }
}