SELECT ?selected_device ?task ?operation ?device_object ?parameter ?hasTask ?obtype
WHERE { 
?selected_device prof:requests ?plan .
?plan prof:consistsOfGoalDescription ?goal .
?goal prof:consistsOfTaskDescription ?task .
?task prof:hasTaskOperator ?operation .
?task  ?hasTask ?device_object .


?device_object prof:hasType ?obtype .
OPTIONAL{ ?task prof:hasTaskParameter ?parameter . }

FILTER(?hasTask = prof:hasTaskObject || ?hasTask = prof:adoptsTaskObjectTemplate)

}