?behav prof:consistsOfGoalDescription ?goal .
?goal prof:consistsOfTaskDescription ?task .
?task prof:hasTaskOperator ?locoperation .
 {
  ?locoperation prof:refersExactlyTo //operation// .
 }
 UNION
  {
     ?locoperation prof:refersAsNewTo //operation// .
  }



{
 
 ?task prof:hasTaskObject ?locdevice_object .
 {
  ?locdevice_object prof:refersExactlyTo ?device_object .
 }
 UNION
 {
  ?locdevice_object prof:refersAsNewTo ?device_object .
 }
 ?device_object prof:hasType ?requesttype .
 FILTER NOT EXISTS
  {
   ?component prof:adoptsTemplate ?device_object .
  }
}
UNION
{
  ?task prof:hasTaskObjectTemplate ?locobjecttemp .
  {
    ?locobjecttemp prof:refersAsNewTo ?objecttemp;
  }
  UNION
  {
    ?locobjecttemp prof:refersExactlyTo ?objecttemp;
  }  
  ?selected_device prof:settles ?device_object . 
  ?objecttemp prof:hasType ?requesttype .
}

?configuration prof:setsUp ?setted .
