?behav prof:consistsOfGoalDescription ?goal .
?goal prof:consistsOfTaskDescription ?task .
?task prof:hasTaskOperator //operation// .
?task prof:hasTaskObject ?device_object .
?device_object prof:hasType //obtype// .