{
?selected_device prof:hasBehavior ?behav .
}
UNION
{
  ?selected_device prof:adoptsTemplate ?template .
  ?template prof:hasBehavior ?behav .
}

OPTIONAL 
{
  ?selected_device prof:hasConfiguration ?conconf .
  ?conconf prof:hasConnection ?aconnect .  
}