//exec// rdf:type owl:NamedIndividual.
//goal// rdf:type owl:NamedIndividual.

?selected_agent rdf:type owl:NamedIndividual.
?operation rdf:type owl:NamedIndividual.
?deviceobject rdf:type owl:NamedIndividual.

prof:performs rdf:type owl:ObjectProperty.
prof:hasTaskExecution rdf:type owl:ObjectProperty.
prof:hasTaskOperator rdf:type owl:ObjectProperty.
prof:hasTaskObject rdf:type owl:ObjectProperty.

?selected_agent prof:performs  //goal//.
//goal// prof:hasTaskExecution //exec//.
//exec// prof:hasTaskOperator ?operation .
//exec// prof:hasTaskObject ?user_object .
