?agent rdf:type owl:NamedIndividual .
?agent oasis:performs //taskexec// .
//param1// oasis:hasTaskExecution //taskexec// .
//taskexec// rdf:type oasis:TaskExecution .
//taskexec// oasis:hasTaskObject //taskexeobject// .
//taskexeobject// rdf:type oasis:TaskObject .
//taskexeobject// oasis:refersExactlyTo //theobject// .
//theobject// oasis:hasType ?requesttype .
//taskexec// oasis:hasTaskOperator //taskexeoperator// .
//taskexeoperator// rdf:type oasis:TaskOperator .
//taskexeoperator// oasis:refersExactlyTo //param2// .