?agent rdf:type owl:NamedIndividual .
?agent prof:performs //taskexec// .
//param1// prof:hasTaskExecution //taskexec// .
//taskexec// rdf:type prof:TaskExecution .
//taskexec// prof:hasTaskObject //taskexeobject// .
//taskexeobject// rdf:type prof:TaskObject .
//taskexeobject// prof:refersExactlyTo //theobject// .
//theobject// prof:hasType ?requesttype .
//taskexec// prof:hasTaskOperator //taskexeoperator// .
//taskexeoperator// rdf:type prof:TaskOperator .
//taskexeoperator// prof:refersExactlyTo //param2// .
?agent prof:hasConfiguration ?conconf .
?conconf prof:hasConnection ?aconnect .
?conconf rdf:type owl:NamedIndividual .
?aconnect rdf:type owl:NamedIndividual .
