SELECT ?task ?plan ?taskObject  ?referObj ?taskObElement ?obPropType ?taskObElementType ?taskOpElement ?taskOpArgElement ?referInp ?taskInpElement ?inpPropType ?taskInpElementType ?referOut ?taskOutElement ?outPropType ?taskOutElementType
WHERE
{
   ?requester  prof:requests ?plan.
   ?plan a prof:PlanDescription.
   ?goal prof:consistsOfTaskDescription ?task .

   ?task prof:hasTaskObject ?taskObject .   
   ?taskObject ?referObj ?taskObElement .
   
   ?taskObElement ?obPropType ?taskObElementType .
   ?obPropType rdfs:subPropertyOf prof:hasType .   

   ?task prof:hasTaskOperator ?taskOperator .
   ?taskOperator prof:refersExactlyTo ?taskOpElement .
   FILTER (?referObj =  prof:refersExactlyTo || ?referObj =  prof:refersAsNewTo )

   OPTIONAL
   {
     ?task prof:hasTaskOperatorArgument ?taskOperatorArgument .
     ?taskOperatorArgument prof:refersExactlyTo ?taskOpArgElement .     
   }
   
   OPTIONAL
   {
     ?task prof:hasTaskActualInputParameter ?taskInputParameter .
     ?taskInputParameter ?referInp ?taskInpElement .
     FILTER (?referInp =  prof:refersExactlyTo || ?referInp =  prof:refersAsNewTo )
     OPTIONAL
     {
       ?taskInpElement ?inpPropType ?taskInpElementType.
       ?inpPropType rdfs:subPropertyOf prof:hasType .
     }
   }

   OPTIONAL
   {
     ?task prof:hasTaskActualOutputParameter ?taskOutputParameter .
     ?taskOutputParameter ?referOut ?taskOutElement .
     FILTER (?referOut =  prof:refersExactlyTo || ?referOut =  prof:refersAsNewTo )
     OPTIONAL
     {
       ?taskIoutElement ?outPropType ?taskOutElementType.
       ?outPropType rdfs:subPropertyOf prof:hasType .
     }
   }


}