SELECT ?task ?plan ?taskObject  ?referObj ?taskObElement ?obPropType ?taskObElementType ?taskOpElement ?taskOpArgElement ?referInp ?taskInpElement ?inpPropType ?taskInpElementType ?referOut ?taskOutElement ?outPropType ?taskOutElementType
WHERE
{
   ?requester  oasis:requests ?plan.
   ?plan a oasis:PlanDescription.
   ?goal oasis:consistsOfTaskDescription ?task .

   ?task oasis:hasTaskObject ?taskObject .   
   ?taskObject ?referObj ?taskObElement .
   
   ?taskObElement ?obPropType ?taskObElementType .
   ?obPropType rdfs:subPropertyOf oasis:hasType .   

   ?task oasis:hasTaskOperator ?taskOperator .
   ?taskOperator oasis:refersExactlyTo ?taskOpElement .
   FILTER (?referObj =  oasis:refersExactlyTo || ?referObj =  oasis:refersAsNewTo )

   OPTIONAL
   {
     ?task oasis:hasTaskOperatorArgument ?taskOperatorArgument .
     ?taskOperatorArgument oasis:refersExactlyTo ?taskOpArgElement .     
   }
   
   OPTIONAL
   {
     ?task oasis:hasTaskActualInputParameter ?taskInputParameter .
     ?taskInputParameter ?referInp ?taskInpElement .
     FILTER (?referInp =  oasis:refersExactlyTo || ?referInp =  oasis:refersAsNewTo )
     OPTIONAL
     {
       ?taskInpElement ?inpPropType ?taskInpElementType.
       ?inpPropType rdfs:subPropertyOf oasis:hasType .
     }
   }

   OPTIONAL
   {
     ?task oasis:hasTaskActualOutputParameter ?taskOutputParameter .
     ?taskOutputParameter ?referOut ?taskOutElement .
     FILTER (?referOut =  oasis:refersExactlyTo || ?referOut =  oasis:refersAsNewTo )
     OPTIONAL
     {
       ?taskIoutElement ?outPropType ?taskOutElementType.
       ?outPropType rdfs:subPropertyOf oasis:hasType .
     }
   }


}