PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prof: <http://www.dmi.unict.it/profeta.owl#>
PREFIX req: <http://www.dmi.unict.it/user-request.owl#>
CONSTRUCT
{   
    <http://www.dmi.unict.it/user-request.owl#alan-task-1-1-1-exec> rdf:type owl:NamedIndividual.
    <http://www.dmi.unict.it/user-request.owl#alan-goal-1-1-1> rdf:type owl:NamedIndividual.

    ?selected_agent rdf:type owl:NamedIndividual.
    ?operation rdf:type owl:NamedIndividual.
    ?deviceobject rdf:type owl:NamedIndividual.

    prof:performs rdf:type owl:ObjectProperty.
    prof:hasTaskExecution rdf:type owl:ObjectProperty.
    prof:hasTaskOperator rdf:type owl:ObjectProperty.
    prof:hasTaskObject rdf:type owl:ObjectProperty.

	?selected_agent prof:performs  <http://www.dmi.unict.it/user-request.owl#alan-goal-1-1-1>.
	<http://www.dmi.unict.it/user-request.owl#alan-goal-1-1-1> prof:hasTaskExecution <http://www.dmi.unict.it/user-request.owl#alan-task-1-1-1-exec>.
	<http://www.dmi.unict.it/user-request.owl#alan-task-1-1-1-exec> prof:hasTaskOperator ?operation .
	<http://www.dmi.unict.it/user-request.owl#alan-task-1-1-1-exec> prof:hasTaskObject ?deviceobject .

} 
 WHERE { 
                                
                 <http://www.dmi.unict.it/user-request.owl#alan-task-1-1-1> prof:hasTaskOperator ?operation .
                 <http://www.dmi.unict.it/user-request.owl#alan-task-1-1-1> prof:hasTaskObject ?object .
                 ?object prof:hasSpaceSpan ?space .
                 ?object prof:hasType ?obtype .
                 ?space prof:hasType  ?spacetype .

                 ?config rdf:type prof:Component_Configuration .
                 ?config prof:configurationProvidedBy  <http://www.dmi.unict.it/alan-config.owl#alan> .
                 ?config prof:setsUp ?user_object .                 
                 ?user_object prof:hasType ?obtype .
                 ?user_object prof:hasSpaceSpan ?space_user .
                 ?space_user prof:hasType ?spacetype .
                 ?user_object prof:setUpFrom ?device_object .

                 ?selected_device prof:hasBehavior ?behav .
                  ?behav prof:hasGoalDescription ?goal .
                 ?goal prof:hasTaskDescription ?task .
                 ?task prof:hasTaskOperator ?operation .
                 ?task prof:hasTaskObject ?device_object .
                 ?device_object prof:hasType ?obtype .

              }