PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prof: <http://www.dmi.unict.it/profeta.owl#>
PREFIX req: <http://www.dmi.unict.it/user-request.owl#>
SELECT ?agent ?operator ?subject
 WHERE { 
                 ?agent prof:hasBehavior ?behav.
                 ?behav prof:hasGoalDescription ?goal.
                 ?goal prof:hasTaskDescription ?task.
                 ?task prof:hasTaskOperator ?operator.
                 
                 <http://www.dmi.unict.it/user-request.owl#user-1-task1-1-1> prof:hasTaskOperator ?operator.
                 <http://www.dmi.unict.it/user-request.owl#user-1-task1-1-1> prof:hasTaskSubject ?subject.
              }