PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prof: <http://www.dmi.unict.it/profeta.owl#>
PREFIX req: <http://www.dmi.unict.it/user-request.owl#>
SELECT  ?selected_agent ?operation ?device_object ?user_object
 WHERE { 
                                
                 <http://www.dmi.unict.it/user-request.owl#user-1-task1-1-1> prof:hasTaskOperator ?operation .
                 <http://www.dmi.unict.it/user-request.owl#user-1-task1-1-1> prof:hasTaskObject ?object .
                 ?object prof:hasSpaceSpan ?space .
                 ?object prof:hasType ?obtype .
                 ?space prof:hasType  ?spacetype .

                 ?config rdf:type prof:Component_Configuration .
                 ?config prof:configurationProvidedBy  <http://www.dmi.unict.it/user-request.owl#user-1> .
                 ?config prof:setsUp ?user_object .                 
                 ?user_object prof:hasType ?obtype .
                 ?user_object prof:hasSpaceSpan ?space_user .
                 ?space_user prof:hasType ?spacetype .
                 ?user_object prof:setUpFrom ?device_object .

                 ?selected_agent prof:hasBehavior ?behav .
                 ?behav prof:hasGoalDescription ?goal .
                 ?goal prof:hasTaskDescription ?task .
                 ?task prof:hasTaskOperator ?operation .
                 ?task prof:hasTaskObject ?agent_subject .
                 ?agent_subject prof:hasType ?obtype .

              }